import{a as L,S,i as u}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="49328321-2a7d7ff1359a5be8e111f7854",v="https://pixabay.com/api/",f=async(t,r,a)=>{try{const s=await L.get(v,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}}),e=s.data.totalHits;return{hits:s.data.hits,totalHits:e}}catch(s){throw console.error(s),s}},H=document.querySelector(".gallery");let P=new S(".gallery a");const p=t=>{const r=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:l,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${s}" class="gallery-link">
          <img src="${a}" alt="${e}" class="gallery-image"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${o}</p>
          <p class="info-item"><b>Views:</b> ${l}</p>
          <p class="info-item"><b>Comments:</b> ${b}</p>
          <p class="info-item"><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");H.insertAdjacentHTML("beforeend",r),P.refresh()},m=()=>{document.querySelector(".loader").classList.add("show")},g=()=>{document.querySelector(".loader").classList.remove("show")};let i=1,y="",d=0;const c=15,$=document.querySelector(".form"),n=document.querySelector(".button-load"),h=document.querySelector(".gallery");n.style.display="none";$.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){u.warning({message:"Please enter a search query!",position:"topRight"});return}r!==y&&(i=1,y=r,h.innerHTML=""),n.style.display="none",m();try{const{hits:a,totalHits:s}=await f(r,i,c);if(d=s,a.length===0){u.info({message:"No images found. Try a different search term!",position:"topRight"});return}p(a),i*c<d?n.style.display="block":n.style.display="none"}catch(a){console.error(a)}finally{g()}});n.addEventListener("click",async()=>{if(i*c>=d){n.style.display="none";return}i+=1,n.style.display="none",m();try{const{hits:t}=await f(y,i,c);p(t),i*c<d?n.style.display="block":n.style.display="none",O()}catch(t){console.error(t)}finally{g()}});const O=()=>{const t=h.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
