import{a as q,i as d,S as v}from"./assets/vendor-BBSqv8W6.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const P="49328321-2a7d7ff1359a5be8e111f7854",$="https://pixabay.com/api/",f=async(t,o,a)=>{try{const s=await q.get($,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a}}),e=s.data.totalHits;return s.data.hits.length===0?(d.info({message:"Sorry, no images match your search. Try again!",position:"topRight"}),{hits:[],totalHits:e}):(e<=o*a&&(document.querySelector(".button-load").style.display="none",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),{hits:s.data.hits,totalHits:e})}catch(s){throw d.error({message:"Failed to fetch images. Please try again later!",position:"topRight"}),console.error(s),s}},m=t=>{const o=document.querySelector(".gallery");if(t.length===0){iziToast.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const a=t.map(({webformatURL:e,largeImageURL:r,tags:l,likes:b,views:w,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${r}" class="gallery-link">
          <img src="${e}" alt="${l}" class="gallery-image"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${b}</p>
          <p class="info-item"><b>Views:</b> ${w}</p>
          <p class="info-item"><b>Comments:</b> ${L}</p>
          <p class="info-item"><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",a),new v(".gallery a").refresh()},h=()=>{document.querySelector(".loader").classList.add("show")},p=()=>{document.querySelector(".loader").classList.remove("show")};let i=1,u="",y=0;const c=15,H=document.querySelector(".form"),n=document.querySelector(".button-load"),R=document.querySelector(".gallery");n.style.display="none";H.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){d.warning({message:"Please enter a search query!",position:"topRight"});return}o!==u&&(i=1,u=o),h();try{const{hits:a,totalHits:s}=await f(o,i,c);y=s,m(a),g(),a.length>0&&i*c<y?n.style.display="block":n.style.display="none"}catch(a){console.error(a)}finally{p()}});n.addEventListener("click",async()=>{if(i*c>=y){n.style.display="none";return}i+=1,h();try{const{hits:t}=await f(u,i,c);m(t),g(),i*c<y?n.style.display="block":n.style.display="none"}catch(t){console.error(t)}finally{p()}});const g=()=>{const t=R.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
